---
- name: Read facts and create OS version status report
  hosts: all 
  vars:
  - results: "results"
  tasks:
  - include: "reports/ios.yml"
    when: "'cisco-ios-devices' in group_names"
  - include: "reports/nxos.yml"
    when: "'cisco-nxos-devices' in group_names"
  - include: "reports/reports-{{dst|default('os-version')}}.yml"
