# Automation Easy wins hands-on
---
- name: Collect facts from devices and save them in a file
  hosts: all
  connection: local 
  vars:
  - results: results
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - snmp_facts:
      host: "{{ansible_host}}"
      version: v2
      community: public
  - copy:
      content: "{{result.ansible_facts}}"
      dest: "{{results}}/{{inventory_hostname}}-snmp.json"
