---
- name: Read facts and create interfaces status report
  hosts: all 
  gather_facts: no
  vars:
  - results: "results"
  tasks:
   - include: "reports/{{src|default('napalm')}}.yml"
   - include: "reports/{{dst|default('interface-status-napalm')}}.yml"
