---
- name: Read facts and create interfaces status report
  hosts: all 
  gather_facts: no
  vars:
  - results: "results"
  tasks:
  - ios_facts: 
    when: "'cisco-ios-devices' in group_names"
  - nxos_facts: 
    when: "'cisco-nxos-devices' in group_names"
  - include: "reports/{{dst|default('interface-status')}}.yml"
