# Automation Easy wins hands-on
---
- name: Collect facts from devices and save them in a file
  hosts: cisco-ios-devices
  connection: local 
  gather_facts: no
  vars:
  - results: results
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - snmp_facts:
       host: "{{ansible_host}}"
       version: v2c
       community: "{{snmp_community}}"
  - copy:
      content: |
         {{hostvars[inventory_hostname]|to_nice_yaml(indent=4)}}
      dest: "{{results}}/{{inventory_hostname}}-snmp.yml"
